version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run: yarn install
  test:
    docker: 
      - image: cimg/node:16.14
    steps:
      - checkout
      - run: yarn install
      - run: yarn run test  

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
