version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.14.0
    steps:
      - checkout
      - run: npm install -g yarn
      - run: yarn install
  test:
    docker:
      - image: circleci/node:16.14.0
    steps:
      - checkout
      - run: yarn run test
