version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run: npm install -g yarn
      - run: yarn install
  test:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run: yarn run test
