version: 1.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run: yarn install
  test:
    steps:
      - checkout
      - run: yarn run test  

workflows:
  version: 1
  build_and_test:
    jobs:
      - build
      - test
